routes/admin.php
<?php
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin'], function () {
    Route::group(['namespace' => 'Auth', 'as' => 'auth.'], function () {
        Route::get('login', 'LoginController@showAdminLoginForm')->name('showLoginForm');
        Route::post('login', 'LoginController@adminLogin')->name('adminLogin');
        Route::post('logout', 'LoginController@adminLogout')->name('adminLogout');
    });


    Route::group(['middleware' => 'auth:admin'], function () {
        //
        Route::get('/', 'DashboardController@index')->name('home');
        Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
        Route::group(['prefix' => 'inventories', 'as' => 'inventories.'], function () {
            Route::get('/', 'InventoryController@dashboard')->name('dashboard');
            Route::group(['prefix' => 'valuation', 'as' => 'valuation.'], function () {
                Route::get('/', 'InventoryValuationController@index')->name('index');
                Route::get('/upload', 'InventoryValuationController@upload')->name('upload');
                Route::post('/upload', 'InventoryValuationController@uploadExcel')->name('upload_excel');
                Route::post('/start_import', 'InventoryValuationController@start_import')->name('start_import');
            });
        });
        Route::group(['prefix' => 'leads', 'as' => 'leads.'], function () {
            Route::get('/', 'LeadsController@dashboard')->name('dashboard');
            Route::get('/all', 'LeadsController@index')->name('index');
            Route::get('/create', 'LeadsController@create')->name('create');
            Route::get('/deleted', 'LeadsController@deleted')->name('deleted');
            Route::get('/import', 'LeadsController@import')->name('import');
            Route::get('/logs', 'LeadsController@logs')->name('logs');

            Route::get('/status', 'LeadsController@status')->name('status');
            Route::get('/status/create', 'LeadsController@statuscreate')->name('status.create');
            Route::post('/status/save', 'LeadsController@statussave')->name('status.save');
            Route::get('/status/edit/{id}', 'LeadsController@editstatus')->name('status.edit');
            Route::get('/status/delete/{id}', 'LeadsController@deletestatus')->name('status.delete');
            Route::get('/tags', 'LeadsController@tags')->name('tags');
            Route::get('/tags/create', 'LeadsController@createtags')->name('tags.create');
            Route::get('/tags/edit/{id}', 'LeadsController@edittags')->name('tags.edit');
            Route::get('/tags/delete/{id}', 'LeadsController@deletetags')->name('tags.delete');
            Route::post('/tags/save', 'LeadsController@savetags')->name('tags.save');
        });
        Route::group(['prefix' => 'customers', 'as' => 'customers.'], function () {
            Route::get('/', 'CustomersController@dashboard')->name('dashboard');
            Route::get('/all', 'CustomersController@index')->name('index');
            Route::get('/create', 'CustomersController@create')->name('create');
            Route::get('/deleted', 'CustomersController@deleted')->name('deleted');
            Route::get('/import', 'CustomersController@import')->name('import');
            Route::get('/logs', 'CustomersController@logs')->name('logs');

            Route::get('/status', 'CustomersController@status')->name('status');
            Route::get('/status/create', 'CustomersController@statuscreate')->name('status.create');
            Route::post('/status/save', 'CustomersController@statussave')->name('status.save');
            Route::get('/status/edit/{id}', 'CustomersController@editstatus')->name('status.edit');
            Route::get('/status/delete/{id}', 'CustomersController@deletestatus')->name('status.delete');
            Route::get('/tags', 'CustomersController@tags')->name('tags');
            Route::get('/tags/create', 'CustomersController@createtags')->name('tags.create');
            Route::get('/tags/edit/{id}', 'CustomersController@edittags')->name('tags.edit');
            Route::get('/tags/delete/{id}', 'CustomersController@deletetags')->name('tags.delete');
            Route::post('/tags/save', 'CustomersController@savetags')->name('tags.save');
        });
        Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
            Route::get('/', 'UsersController@dashboard')->name('dashboard');
            Route::get('/all', 'UsersController@index')->name('index');
            Route::get('/create', 'UsersController@create')->name('create');
            Route::get('/deleted', 'UsersController@deleted')->name('deleted');
            Route::get('/roles', 'UsersController@roles')->name('roles');
            Route::get('/logs', 'UsersController@logs')->name('logs');
        });
        Route::group(['prefix' => 'calendar', 'as' => 'calendar.'], function () {
            Route::get('/', 'CalendarController@dashboard')->name('dashboard');
            Route::get('/events', 'CalendarController@events')->name('events');
            Route::get('/types', 'CalendarController@types')->name('types');
            Route::get('/notifications', 'CalendarController@notifications')->name('notifications');
            Route::get('/logs', 'CalendarController@logs')->name('logs');
        });
        Route::group(['prefix' => 'locations', 'as' => 'locations.'], function () {
            Route::get('/', 'LocationController@index')->name('index');
            Route::get('/create', 'LocationController@create')->name('create');
            Route::get('/deleted', 'LocationController@deleted')->name('deleted');
            Route::get('/types', 'LocationController@types')->name('types');
            Route::get('/logs', 'LocationController@logs')->name('logs');
        });
        Route::group(['prefix' => 'reports', 'as' => 'reports.'], function () {
            Route::get('/logs', 'ReportController@logs')->name('logs');
        });
        Route::group(['prefix' => 'documents', 'as' => 'documents.'], function () {
            Route::get('/index', 'ReportController@index')->name('index');
            Route::get('/create', 'ReportController@create')->name('create');
            Route::get('/deleted', 'ReportController@deleted')->name('deleted');
            Route::get('/tags', 'ReportController@tags')->name('tags');
            Route::get('/logs', 'ReportController@logs')->name('logs');
        });
        Route::group(['prefix' => 'transactions', 'as' => 'transactions.'], function () {
            Route::get('/index', 'TransactionController@index')->name('index');
            Route::get('/create_invoice', 'TransactionController@create_invoice')->name('create_invoice');
            Route::get('/create_quote', 'TransactionController@create_quote')->name('create_quote');
            Route::get('/deleted', 'TransactionController@deleted')->name('deleted');
            Route::get('/tags', 'TransactionController@tags')->name('tags');
            Route::get('/logs', 'TransactionController@logs')->name('logs');
        });
        Route::group(['prefix' => 'settings', 'as' => 'settings.'], function () {
            Route::get('/profile', 'SettingsController@profile')->name('profile');
        });
    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Events\InventoryImportEvent;


Route::get('/inventory/share/{id}', 'OtherController@inventoryShare')->name('inventory.share');
Route::get('/thank_you', 'OtherController@thankyou')->name('thank_you');
Route::post('/inventory/leads/generate', 'OtherController@leadGenerate')->name('inventory.lead_generate');
Route::get('/facebook/webhooks/{category}', 'FacebookWebhookController@webhook');
Route::post('/facebook/webhooks/{category}', 'FacebookWebhookController@webhook');
Route::get('/remove_error_inventories', function () {
    foreach (App\Models\Inventory::all() as $inventory) {
        echo $inventory->price;
        echo '<br/>';
        if (!is_numeric($inventory->price)) {
            dd($inventory);
            $inventory->delete();
        }
    }
});
Route::get('/language/{lang}', function ($lang) {
    // return view('welcome');
    session(['my_locale' => $lang]);
    // dd(session('my_locale'));
    return redirect(route('home'));
})->name('language');
Route::get('/lang_currency', 'Controller@setLangCurrency')->name('lang_currency');


Route::group(['prefix' => 'valuation'], function () {
    Route::get('/search', 'ValuationController@search');
    Route::get('/makes', 'ValuationController@makes');
    Route::get('/filter_params', 'ValuationController@filter_params');
    Route::get('/{make}/models', 'ValuationController@models');
    Route::get('/{country}/cities', 'ValuationController@cities');
});
// makes

Route::group(['prefix' => 'car2db'], function () {
    //
    Route::get('/vehicle_types', 'Car2DBController@getVehicleTypes');
    Route::get('/transmissions', 'Car2DBController@transmissions');
    Route::get('/{type}/makes', 'Car2DBController@getMakes');
    Route::get('/{make}/models', 'Car2DBController@getModelsByMake');
    Route::get('/{type}/{make}/models', 'Car2DBController@getModels');
    Route::get('/{type}/{model}/generations', 'Car2DBController@getGenerations');
    Route::get('/{type}/{model}/{generation}/series', 'Car2DBController@getSeries');
    Route::get('/{type}/{model}/{serie}/trims', 'Car2DBController@getTrims');
    Route::get('/{type}/{trim}/equipments', 'Car2DBController@getEquipments');
    Route::get('/{type}/{trim}/specifications', 'Car2DBController@getSpecifications');
});

app/Http/Controllers/Admin/TransactionController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class TransactionController extends Controller
{
    //
}

resources/views/admin/transactions/createtags.blade.php
@extends('layouts.admin')


@section('page_header')
<div class="page-header page-header-light">
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex">
            <h4><i class="icon-arrow-left52 mr-2"></i> <span
                    class="font-weight-semibold">{{ __('app.inventories') }}</span> - Create New Tag</h4>
            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>

        {{--  <div class="header-elements d-none">
            <div class="d-flex justify-content-center">
                <a href="{{ route('admin.inventories.tags.create') }}" class="btn btn-link btn-float font-size-sm
        font-weight-semibold text-default legitRipple">
        <i class="icon-plus3 text-pink-300"></i>
        <span>{{ __('app.add_new') }}</span>
        </a>

        <a href="#" class="btn btn-link btn-float font-size-sm font-weight-semibold text-default legitRipple">
            <i class="icon-trash text-pink-300"></i>
            <span>Clear All</span>
        </a>
    </div>
</div> --}}
</div>

<div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
    <div class="d-flex">
        <div class="breadcrumb">
            <a href="{{ route('admin.dashboard') }}" class="breadcrumb-item"><i
                    class="icon-home2 mr-2"></i>{{ __('app.home') }}</a>
            <a href="{{ route('admin.inventories.index') }}" class="breadcrumb-item"><i class="fas fa-car mr-2"></i>
                Inventories</a>
            <a href="{{ route('admin.inventories.tags') }}" class="breadcrumb-item"><i class="fas fa-car mr-2"></i> Tag
                Management</a>
            <span class="breadcrumb-item active">Create New Tag</span>
        </div>

        <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
    </div>

    {{--  <div class="header-elements d-none">
            <div class="breadcrumb justify-content-center">
                <a href="#" class="breadcrumb-elements-item">
                    <i class="icon-comment-discussion mr-2"></i>
                    Support
                </a>

                <div class="breadcrumb-elements-item dropdown p-0">
                    <a href="#" class="breadcrumb-elements-item dropdown-toggle" data-toggle="dropdown">
                        <i class="icon-gear mr-2"></i>
                        Settings
                    </a>

                    <div class="dropdown-menu dropdown-menu-right">
                        <a href="#" class="dropdown-item"><i class="icon-user-lock"></i> Account security</a>
                        <a href="#" class="dropdown-item"><i class="icon-statistics"></i> Analytics</a>
                        <a href="#" class="dropdown-item"><i class="icon-accessibility"></i> Accessibility</a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item"><i class="icon-gear"></i> All settings</a>
                    </div>
                </div>
            </div>
        </div>  --}}
</div>
</div>
@endsection


@section('page_content')
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            {{--  <div class="card-header header-elements-inline">
                    <div class="header-elements">
                        <div class="list-icons">
                            <a class="list-icons-item" data-action="collapse"></a>
                            <a class="list-icons-item" data-action="reload"></a>
                            <a class="list-icons-item" data-action="remove"></a>
                        </div>
                    </div>
                </div>  --}}

            <div class="card-body">
                <form action="{{ route('admin.inventories.tags.save') }}" method="POST">
                    @csrf
                    <div class="row">
                        <div class="col-md-12">
                            <fieldset>
                                <legend class="font-weight-semibold"><i class="icon-truck mr-2"></i> Tag details
                                </legend>

                                <div class="form-group row">
                                    <label class="col-lg-3 col-form-label">Tag name:</label>
                                    <div class="col-lg-9">
                                        <input type="text" placeholder="Tag name..." name="tag_name"
                                            class="form-control">
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-lg-3 col-form-label">{{ __('app.label_color') }}</label>
                                    <div class="col-lg-9">
                                        {{--  <input type="text" placeholder="Status color..." name="color" class="form-control">  --}}
                                        <select name="color" class="form-control">
                                            <option value="">Tag color...</option>
                                            <option value="primary">primary</option>
                                            <option value="danger">danger</option>
                                            <option value="success">success</option>
                                            <option value="warning">warning</option>
                                            <option value="info">info</option>
                                            <option value="pink">pink</option>
                                            <option value="purple">purple</option>
                                            <option value="violet">violet</option>
                                            <option value="indigo">indigo</option>
                                            <option value="blue">blue</option>
                                            <option value="teal">teal</option>
                                            <option value="green">green</option>
                                            <option value="orange">orange</option>
                                            <option value="brown">brown</option>
                                            <option value="grey">grey</option>
                                            <option value="slate">slate</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-lg-3 col-form-label">&nbsp;</label>
                                    <div class="col-lg-9">
                                        <button type="submit"
                                            class="btn btn-primary legitRipple">{{ __('app.save') }}</button>
                                    </div>
                                </div>


                            </fieldset>
                        </div>
                    </div>
                    {{--  <div class="text-right">  --}}
                    {{--  <button type="submit" class="btn btn-primary legitRipple">Submit form <i class="icon-paperplane ml-2"></i></button>  --}}
                    {{--  </div>  --}}
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/transactions/tags.blade.php
@extends('layouts.admin')


@section('page_header')
<div class="page-header page-header-light">
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex">
            <h4><i class="icon-arrow-left52 mr-2"></i> <span
                    class="font-weight-semibold">{{ __('app.inventories') }}</span> - {{ __('app.status_management') }}
            </h4>
            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>

        <div class="header-elements d-none">
            <div class="d-flex justify-content-center">
                <a href="{{ route('admin.inventories.tags.create') }}"
                    class="btn btn-link btn-float font-size-sm font-weight-semibold text-default legitRipple">
                    <i class="icon-plus3 text-pink-300"></i>
                    <span>{{ __('app.add_new') }}</span>
                </a>

                <a href="#" class="btn btn-link btn-float font-size-sm font-weight-semibold text-default legitRipple">
                    <i class="icon-trash text-pink-300"></i>
                    <span>Clear All</span>
                </a>
            </div>
        </div>
    </div>

    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="{{ route('admin.dashboard') }}" class="breadcrumb-item"><i
                        class="icon-home2 mr-2"></i>{{ __('app.home') }}</a>
                <a href="{{ route('admin.inventories.index') }}" class="breadcrumb-item"><i class="fas fa-car mr-2"></i>
                    Inventories</a>
                <span class="breadcrumb-item active">{{ __('app.tags') }}</span>
            </div>

            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>

        {{--  <div class="header-elements d-none">
            <div class="breadcrumb justify-content-center">
                <a href="#" class="breadcrumb-elements-item">
                    <i class="icon-comment-discussion mr-2"></i>
                    Support
                </a>

                <div class="breadcrumb-elements-item dropdown p-0">
                    <a href="#" class="breadcrumb-elements-item dropdown-toggle" data-toggle="dropdown">
                        <i class="icon-gear mr-2"></i>
                        Settings
                    </a>

                    <div class="dropdown-menu dropdown-menu-right">
                        <a href="#" class="dropdown-item"><i class="icon-user-lock"></i> Account security</a>
                        <a href="#" class="dropdown-item"><i class="icon-statistics"></i> Analytics</a>
                        <a href="#" class="dropdown-item"><i class="icon-accessibility"></i> Accessibility</a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item"><i class="icon-gear"></i> All settings</a>
                    </div>
                </div>
            </div>
        </div>  --}}
    </div>
</div>
@endsection


@section('page_content')
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">All Tags</h5>
                <div class="header-elements">
                    <div class="list-icons">
                        <a class="list-icons-item" data-action="collapse"></a>
                        <a class="list-icons-item" data-action="reload"></a>
                        <a class="list-icons-item" data-action="remove"></a>
                    </div>
                </div>
            </div>



            <div class="table-responsive">
                <table class="table text-nowrap">
                    <thead>
                        <tr>
                            <th>Tag Name</th>
                            <th>Tag Color</th>
                            <th>CreatedBy</th>
                            <th>{{ __('app.action') }}</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($tags as $tag)
                        <tr>
                            <td>{{ $tag->tag_name }}</td>
                            <td class="text-{{ $tag->color }}">{{ $tag->color }}</td>
                            <td>{{ $tag->created_by }}</td>
                            <td class="">
                                <a class="mr-1"
                                    href="{{ route('admin.inventories.tags.edit', $tag->id) }}">{{ __('app.edit') }}</a>
                                <a class="mr-1"
                                    href="{{ route('admin.inventories.tags.delete', $tag->id) }}">{{ __('app.delete') }}</a>
                            </td>
                        </tr>
                        @endforeach

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection