routes/admin.php
<?php
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin'], function () {
    Route::group(['namespace' => 'Auth', 'as' => 'auth.'], function () {
        Route::get('login', 'LoginController@showAdminLoginForm')->name('showLoginForm');
        Route::post('login', 'LoginController@adminLogin')->name('adminLogin');
        Route::post('logout', 'LoginController@adminLogout')->name('adminLogout');
    });


    Route::group(['middleware' => 'auth:admin'], function () {
        //
        Route::get('/', 'DashboardController@index')->name('home');
        Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
        Route::group(['prefix' => 'inventories', 'as' => 'inventories.'], function () {
            Route::get('/', 'InventoryController@dashboard')->name('dashboard');
            Route::group(['prefix' => 'valuation', 'as' => 'valuation.'], function () {
                Route::get('/', 'InventoryValuationController@index')->name('index');
                Route::get('/upload', 'InventoryValuationController@upload')->name('upload');
                Route::post('/upload', 'InventoryValuationController@uploadExcel')->name('upload_excel');
                Route::post('/start_import', 'InventoryValuationController@start_import')->name('start_import');
            });
        });
        Route::group(['prefix' => 'leads', 'as' => 'leads.'], function () {
            Route::get('/', 'LeadsController@dashboard')->name('dashboard');
            Route::get('/all', 'LeadsController@index')->name('index');
            Route::get('/create', 'LeadsController@create')->name('create');
            Route::get('/deleted', 'LeadsController@deleted')->name('deleted');
            Route::get('/import', 'LeadsController@import')->name('import');
            Route::get('/logs', 'LeadsController@logs')->name('logs');

            Route::get('/status', 'LeadsController@status')->name('status');
            Route::get('/status/create', 'LeadsController@statuscreate')->name('status.create');
            Route::post('/status/save', 'LeadsController@statussave')->name('status.save');
            Route::get('/status/edit/{id}', 'LeadsController@editstatus')->name('status.edit');
            Route::get('/status/delete/{id}', 'LeadsController@deletestatus')->name('status.delete');
            Route::get('/tags', 'LeadsController@tags')->name('tags');
            Route::get('/tags/create', 'LeadsController@createtags')->name('tags.create');
            Route::get('/tags/edit/{id}', 'LeadsController@edittags')->name('tags.edit');
            Route::get('/tags/delete/{id}', 'LeadsController@deletetags')->name('tags.delete');
            Route::post('/tags/save', 'LeadsController@savetags')->name('tags.save');
        });
        Route::group(['prefix' => 'customers', 'as' => 'customers.'], function () {
            Route::get('/', 'CustomersController@dashboard')->name('dashboard');
            Route::get('/all', 'CustomersController@index')->name('index');
            Route::get('/create', 'CustomersController@create')->name('create');
            Route::get('/deleted', 'CustomersController@deleted')->name('deleted');
            Route::get('/import', 'CustomersController@import')->name('import');
            Route::get('/logs', 'CustomersController@logs')->name('logs');

            Route::get('/status', 'CustomersController@status')->name('status');
            Route::get('/status/create', 'CustomersController@statuscreate')->name('status.create');
            Route::post('/status/save', 'CustomersController@statussave')->name('status.save');
            Route::get('/status/edit/{id}', 'CustomersController@editstatus')->name('status.edit');
            Route::get('/status/delete/{id}', 'CustomersController@deletestatus')->name('status.delete');
            Route::get('/tags', 'CustomersController@tags')->name('tags');
            Route::get('/tags/create', 'CustomersController@createtags')->name('tags.create');
            Route::get('/tags/edit/{id}', 'CustomersController@edittags')->name('tags.edit');
            Route::get('/tags/delete/{id}', 'CustomersController@deletetags')->name('tags.delete');
            Route::post('/tags/save', 'CustomersController@savetags')->name('tags.save');
        });
        Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
            Route::get('/', 'UsersController@dashboard')->name('dashboard');
            Route::get('/all', 'UsersController@index')->name('index');
            Route::get('/create', 'UsersController@create')->name('create');
            Route::get('/deleted', 'UsersController@deleted')->name('deleted');
            Route::get('/roles', 'UsersController@roles')->name('roles');
            Route::get('/logs', 'UsersController@logs')->name('logs');
        });
        Route::group(['prefix' => 'calendar', 'as' => 'calendar.'], function () {
            Route::get('/', 'CalendarController@dashboard')->name('dashboard');
            Route::get('/events', 'CalendarController@events')->name('events');
            Route::get('/types', 'CalendarController@types')->name('types');
            Route::get('/notifications', 'CalendarController@notifications')->name('notifications');
            Route::get('/logs', 'CalendarController@logs')->name('logs');
        });
        Route::group(['prefix' => 'locations', 'as' => 'locations.'], function () {
            Route::get('/', 'LocationController@index')->name('index');
            Route::get('/create', 'LocationController@create')->name('create');
            Route::get('/deleted', 'LocationController@deleted')->name('deleted');
            Route::get('/types', 'LocationController@types')->name('types');
            Route::get('/logs', 'LocationController@logs')->name('logs');
        });
        Route::group(['prefix' => 'reports', 'as' => 'reports.'], function () {
            Route::get('/logs', 'ReportController@logs')->name('logs');
        });
        Route::group(['prefix' => 'documents', 'as' => 'documents.'], function () {
            Route::get('/index', 'ReportController@index')->name('index');
            Route::get('/create', 'ReportController@create')->name('create');
            Route::get('/deleted', 'ReportController@deleted')->name('deleted');
            Route::get('/tags', 'ReportController@tags')->name('tags');
            Route::get('/logs', 'ReportController@logs')->name('logs');
        });
        Route::group(['prefix' => 'transactions', 'as' => 'transactions.'], function () {
            Route::get('/index', 'TransactionController@index')->name('index');
            Route::get('/create_invoice', 'TransactionController@create_invoice')->name('create_invoice');
            Route::get('/create_quote', 'TransactionController@create_quote')->name('create_quote');
            Route::get('/deleted', 'TransactionController@deleted')->name('deleted');
            Route::get('/tags', 'TransactionController@tags')->name('tags');
            Route::get('/logs', 'TransactionController@logs')->name('logs');
        });
        Route::group(['prefix' => 'settings', 'as' => 'settings.'], function () {
            Route::get('/profile', 'SettingsController@profile')->name('profile');
        });
    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Events\InventoryImportEvent;


Route::get('/inventory/share/{id}', 'OtherController@inventoryShare')->name('inventory.share');
Route::get('/thank_you', 'OtherController@thankyou')->name('thank_you');
Route::post('/inventory/leads/generate', 'OtherController@leadGenerate')->name('inventory.lead_generate');
Route::get('/facebook/webhooks/{category}', 'FacebookWebhookController@webhook');
Route::post('/facebook/webhooks/{category}', 'FacebookWebhookController@webhook');
Route::get('/remove_error_inventories', function () {
    foreach (App\Models\Inventory::all() as $inventory) {
        echo $inventory->price;
        echo '<br/>';
        if (!is_numeric($inventory->price)) {
            dd($inventory);
            $inventory->delete();
        }
    }
});
Route::get('/language/{lang}', function ($lang) {
    // return view('welcome');
    session(['my_locale' => $lang]);
    // dd(session('my_locale'));
    return redirect(route('home'));
})->name('language');
Route::get('/lang_currency', 'Controller@setLangCurrency')->name('lang_currency');


Route::group(['prefix' => 'valuation'], function () {
    Route::get('/search', 'ValuationController@search');
    Route::get('/makes', 'ValuationController@makes');
    Route::get('/filter_params', 'ValuationController@filter_params');
    Route::get('/{make}/models', 'ValuationController@models');
    Route::get('/{country}/cities', 'ValuationController@cities');
});
// makes

Route::group(['prefix' => 'car2db'], function () {
    //
    Route::get('/vehicle_types', 'Car2DBController@getVehicleTypes');
    Route::get('/transmissions', 'Car2DBController@transmissions');
    Route::get('/{type}/makes', 'Car2DBController@getMakes');
    Route::get('/{make}/models', 'Car2DBController@getModelsByMake');
    Route::get('/{type}/{make}/models', 'Car2DBController@getModels');
    Route::get('/{type}/{model}/generations', 'Car2DBController@getGenerations');
    Route::get('/{type}/{model}/{generation}/series', 'Car2DBController@getSeries');
    Route::get('/{type}/{model}/{serie}/trims', 'Car2DBController@getTrims');
    Route::get('/{type}/{trim}/equipments', 'Car2DBController@getEquipments');
    Route::get('/{type}/{trim}/specifications', 'Car2DBController@getSpecifications');
});

app/Models/Customer.php
<?php

namespace App\Models;

use Jenssegers\Mongodb\Eloquent\Model;

class Customer extends Model
{
    //
    protected $appends = ['name', 'profile_image_src', 'id'];

    public function getNameAttribute()
    {
        return $this->attributes['first_name'] . ' ' . $this->attributes['middle_name'] . ' ' . $this->attributes['last_name'];
    }
    public function getProfileImageSrcAttribute()
    {
        if (isset($this->attributes['profile_image'])) {
            return $this->attributes['profile_image'] ? asset($this->attributes['profile_image']) : asset('/global_assets/images/placeholders/placeholder.jpg');
        }
        return "https://ui-avatars.com/api/?bold=true&color=ffffff&background=139ff0&name=" . $this->attributes['first_name'] . '+' . $this->attributes['last_name'];
    }

    public function phone_number_details()
    {
        # code...
        return $this->hasMany('App\Models\CustomerPhoneNumber', 'customer_id', '_id');
    }
    public function email_details()
    {
        # code...
        return $this->hasMany('App\Models\CustomerEmail', 'customer_id', '_id');
    }

    public function avgLookingPrice()
    {
        $avgPrice = LeadInterest::where('lead_id', $this->id)
            ->leftJoin('currencies', 'lead_interests.price_currency', 'currencies.id')
            ->avg(DB::raw('(lead_interests.price_from*currencies.currency_rate + lead_interests.price_to*currencies.currency_rate)/2'));
        return number_format($avgPrice, 0, '.', ',');
    }
    public function minLookingPrice()
    {
        $minPrice = LeadInterest::where('lead_id', $this->id)
            ->leftJoin('currencies', 'lead_interests.price_currency', 'currencies.id')
            ->min(DB::raw('(lead_interests.price_from*currencies.currency_rate)'));
        return number_format($minPrice, 0, '.', ',');
    }
    public function maxLookingPrice()
    {
        $maxPrice = LeadInterest::where('lead_id', $this->id)
            ->leftJoin('currencies', 'lead_interests.price_currency', 'currencies.id')
            ->max(DB::raw('(lead_interests.price_to*currencies.currency_rate)'));
        return number_format($maxPrice, 0, '.', ',');
    }

    public function isHot()
    {
        $interests = LeadInterest::where('lead_id', $this->id)->get();
        $isHot = false;
        foreach ($interests as $interest) {
            if ($interest->looking_to && ($interest->price_from || $interest->price_to)) {
                $isHot = true;
            }
        }
        return $isHot;
    }
}

app/Http/Controllers/Admin/CustomersController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CustomersController extends Controller
{
    //
    public function status(){
        $statuses = InventoryStatus::all();
        return view('admin.inventories.status', compact('statuses'));
    }
    public function statuscreate(){
        $statuses = InventoryStatus::all();
        return view('admin.inventories.createstatus', compact('statuses'));
    }
    public function editstatus($id){
        $status = InventoryStatus::find($id);
        return view('admin.inventories.editstatus', compact('status'));
    }
    public function deletestatus($id){
        $status = InventoryStatus::find($id);
        if($status){
            $status->delete();
            return redirect()->back()->with('success', "You removed a inventory status successfully!");
        }
        else{
            abort(404);
        }

    }

    public function statussave(Request $request){
        if(isset($request->id)){
            $status = InventoryStatus::find($request->id);
        }
        else{
            $status = new InventoryStatus;
        }

        $status->status_name = $request->status_name;
        $status->color = $request->color;
        $status->user_id = 0;
        $status->save();
        if(isset($request->id)){
            return redirect(route('admin.inventories.status'))->with('success', "You updated a inventory status successfully!");
        }
        return redirect()->back()->with('success', "You saved a inventory status successfully!");
    }


    public function tags(){
        $tags = InventoryTag::all();
        return view('admin.inventories.tags', compact('tags'));
    }

    public function createtags (){
        return view('admin.inventories.createtags');
    }

    public function savetags (Request $request){
        if(isset($request->id)){
            $tag = InventoryTag::find($request->id);
        }
        else{
            $tag = new InventoryTag;
        }

        $tag->tag_name = $request->tag_name;
        $tag->color = $request->color;
        $tag->user_id = 0;
        $tag->save();
        if(isset($request->id)){
            return redirect(route('admin.inventories.tags'))->with('success', "You updated a inventory tag successfully!");
        }
        return redirect()->back()->with('success', "You saved a inventory tag successfully!");
    }

    public function edittags($id){
        $tag = InventoryTag::find($id);
        return view('admin.inventories.edittag', compact('tag'));
    }
}

resources/views/customers/tags/create.blade.php
@extends('layouts.app')

@section('page-title')
<!-- BEGIN: Breadcrumb -->
<h2 class="text-lg font-medium mr-auto">
    {{ __('app.customers') }} - {{__('app.create_new_tag')}}
</h2>
<!-- END: Breadcrumb -->
@endsection

@section('page_header')
<div class="intro-y p-5 mb-5 flex flex-wrap items-center border-b">

    <div class="-intro-x breadcrumb mr-auto hidden sm:flex">
        <a href="{{ route('dashboard') }}" class="flex items-center"><i data-feather="home" class="mr-2"></i>{{ __('app.home') }}</a>
        <i data-feather="chevron-right" class="breadcrumb__icon"></i> 
        <a href="{{ route('customers.tags') }}" class="breadcrumb">{{ __('app.tag_management') }}</a>
        <i data-feather="chevron-right" class="breadcrumb__icon"></i> 
        <a href="#" class="breadcrumb--active">{{__('app.create_new_tag')}}</a>
    </div>

</div>
@endsection

@section('page_content')

<div class="grid grid-cols-12 gap-6 mt-5">
    <div class="intro-y box mt-5 col-span-12 lg:col-span-12">
        <div class="flex flex-col sm:flex-row items-center p-5 border-b border-gray-200">
            <h2 class="font-medium text-base mr-auto">
                {{__('app.tag_details')}}
            </h2>
        </div>
        <div class="p-5">
            <form action="{{ route('customers.tags.save') }}" method="POST" id="create_form">
                @csrf
                <div class="grid grid-cols-12 gap-6 mt-5">
                    <label class="col-span-12 lg:col-span-3">{{__('app.tag_name')}}:</label>
                    <div class="col-span-12 lg:col-span-9">
                        <input type="text" placeholder="Tag name..." name="tag_name" id="tag_name"
                            class="input w-full border">
                    </div>
                </div>
                <div class="grid grid-cols-12 gap-6 mt-5">
                    <label class="col-span-12 lg:col-span-3">{{ __('app.label_color') }}:</label>
                    <div class="col-span-12 lg:col-span-9">
                        <select name="color" class="input border mr-2 w-full" id="color_selector">
                            <option value=""></option>
                            @foreach(config('constants.colors') as $color)
                                <option value="{{$color['value']}}">{{ $color['value'] }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="grid grid-cols-12 gap-6 mt-5">
                    <label class="col-span-12 lg:col-span-3"></label>
                    <div class="col-span-12 lg:col-span-9">
                        <button type="submit" class="button w-40 mr-2 mb-2 flex items-center justify-center bg-theme-1 text-white">
                            <i data-feather="save" class="mr-2"></i>
                                {{ __('app.save') }}
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@endsection
@section('scripts_after')
<script>
    $(document).ready(function(){
        function colorDropdownFormat(state) {
            if (!state.id) {
                return state.text;
            }
            var baseUrl = "/user/pages/images/flags";
            var $state = $(
                '<span class="py-1 px-2 rounded-full text-xs text-theme-6 font-medium bg bg-' + state.text+ '">&nbsp;&nbsp;</span>&nbsp;<span>' + state.text.charAt(0).toUpperCase() + state.text.slice(1) + '</span>'
            );
            return $state;
        };
        $("#color_selector").select2({
            placeholder: 'Select an color',
            templateResult: colorDropdownFormat
        })
        $("#create_form").submit(function(e){
            e.preventDefault()
            $.post("{{ route('customers.tags.save') }}", {
                _token: "{{ csrf_token() }}",
                tag_name : $("#tag_name").val(),
                color : $("#color_selector").val(),
            }, function(result){
                $.confirm({
                    title: 'Thank you!',
                    content: '<p>You created new tag successfully! Do you want to create another tags continue?</p>',
                    theme: 'supervan',
                    buttons: {
                        confirm: function () {
                            location.href = '/customers/tags/'
                        },
                        cancel: function () {
                            $("#tag_name").val('')
                        },
                    }
                });
            })
        })
    });
</script>
@endsection

resources/views/customers/tags/edit.blade.php
@extends('layouts.app')

@section('page-title')
<!-- BEGIN: Breadcrumb -->
<h2 class="text-lg font-medium mr-auto">
    {{ __('app.customers') }} - {{__('app.edit_tag')}}
</h2>
<!-- END: Breadcrumb -->
@endsection

@section('page_header')
<div class="intro-y p-5 mb-5 flex flex-wrap items-center border-b">

    <div class="-intro-x breadcrumb mr-auto hidden sm:flex">
        <a href="{{ route('dashboard') }}" class="flex items-center"><i data-feather="home" class="mr-2"></i>{{ __('app.home') }}</a>
        <i data-feather="chevron-right" class="breadcrumb__icon"></i>
        <a href="{{ route('customers.index') }}" class="flex items-center">{{ __('app.customers') }}</a>
        <i data-feather="chevron-right" class="breadcrumb__icon"></i> 
        <a href="{{ route('customers.tags') }}" class="breadcrumb">{{ __('app.tag_management') }}</a>
        <i data-feather="chevron-right" class="breadcrumb__icon"></i> 
        <a href="#" class="breadcrumb--active">{{__('app.edit_tag')}}</a>
    </div>

</div>
@endsection


@section('page_content')

<div class="grid grid-cols-12 gap-6 mt-5">
    <div class="intro-y box mt-5 col-span-12 lg:col-span-12">
        <div class="flex flex-col sm:flex-row items-center p-5 border-b border-gray-200">
            <h2 class="font-medium text-base mr-auto">
                {{__('app.tag_details')}}
            </h2>
        </div>
        <div class="p-5">
            <form action="{{ route('customers.tags.save') }}" method="POST" id="create_form">
                @csrf
                <input type="hidden" name="id" value="{{ $tag->id }}" />
                <div class="grid grid-cols-12 gap-6 mt-5">
                    <label class="col-span-12 lg:col-span-3">{{__('app.tag_name')}}:</label>
                    <div class="col-span-12 lg:col-span-9">
                        <input type="text" placeholder="Tag name..." name="tag_name" id="tag_name"
                            class="input w-full border" value="{{ $tag->tag_name }}">
                    </div>
                </div>
                <div class="grid grid-cols-12 gap-6 mt-5">
                    <label class="col-span-12 lg:col-span-3">{{ __('app.label_color') }}:</label>
                    <div class="col-span-12 lg:col-span-9">
                        <select name="color" class="input border mr-2 w-full" id="color_selector">
                            <option value=""></option>
                            @foreach(config('constants.colors') as $color)
                                <option value="{{$color['value']}}" @if($tag->color == $color['value']) selected @endif>{{ $color['value'] }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="grid grid-cols-12 gap-6 mt-5">
                    <label class="col-span-12 lg:col-span-3"></label>
                    <div class="col-span-12 lg:col-span-9">
                        <button type="submit" class="button w-40 mr-2 mb-2 flex items-center justify-center bg-theme-1 text-white">
                            <i data-feather="save" class="mr-2"></i>
                            {{ __('app.save') }}
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

@section('scripts_after')
<script>
    $(document).ready(function(){
        function colorDropdownFormat(state) {
            if (!state.id) {
                return state.text;
            }
            var baseUrl = "/user/pages/images/flags";
            var $state = $(
                '<span class="py-1 px-2 rounded-full text-xs text-theme-6 font-medium bg bg- bg-' + state.text+ '">&nbsp;&nbsp;</span>&nbsp;<span>' + state.text.charAt(0).toUpperCase() + state.text.slice(1) + '</span>'
            );
            return $state;
        };
        $("#color_selector").select2({
            placeholder: 'Select an color',
            templateResult: colorDropdownFormat
        })
    });
</script>
@endsection

resources/views/customers/tags/index.blade.php
@extends('layouts.app')

@section('page-title')
<!-- BEGIN: Breadcrumb -->
<h2 class="text-lg font-medium mr-auto">
    {{ __('app.customers') }} - {{ __('app.tag_management') }}
</h2>
<!-- END: Breadcrumb -->
@endsection

@section('page_header')

<div class="intro-y flex flex-wrap items-center border-b">

    <div class="-intro-x breadcrumb mr-auto hidden sm:flex">
        <a href="" class="flex items-center"><i data-feather="home" class="mr-2"></i>{{ __('app.customers') }}</a> 
        <i data-feather="chevron-right" class="breadcrumb__icon"></i> 
        <a href="" class="breadcrumb--active">{{ __('app.tag_management') }}</a> 
    </div>
    <div class="p-5" id="icon-button">
        <div class="preview flex flex-wrap">
            <a href="{{ route('customers.tags.create') }}"
                class="button w-40 mr-2 mb-2 flex items-center justify-center bg-theme-1 text-white">
                <i data-feather="plus-circle" class="mr-2"></i>
                {{ __('app.add_new') }}
            </a>
        </div>
    </div>
</div>

@endsection


@section('page_content')
<div class="grid grid-cols-12 gap-6 mt-5">
    <div class="intro-y box mt-5 col-span-12 lg:col-span-12">
        <div class="flex flex-col sm:flex-row items-center p-5 border-b border-gray-200">
            <h2 class="font-medium text-base mr-auto">
                {{__('app.all_tags')}}
            </h2>
        </div>
        <div class="p-5" id="bordered-table">
            <div class="preview">
                <div class="overflow-x-auto">
                    <table class="table">
                        <thead>
                            <tr>
                                <th class="border border-b-2 whitespace-no-wrap">Tag Name</th>
                                <th class="border border-b-2 whitespace-no-wrap">Tag Color</th>
                                <th class="border border-b-2 whitespace-no-wrap">{{__('app.created_by')}}</th>
                                <th class="border border-b-2 whitespace-no-wrap">{{ __('app.action') }}</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($tags as $tag)
                            <tr>
                                <td class="border">{{ $tag->tag_name }}</td>
                                <td class="border">
                                    <span class='py-1 px-2 rounded-full text-xs bg-{{ $tag->color }} text-white cursor-pointer font-medium'>
                                        {{ $tag->color }}
                                    </span>
                                </td>
                                <td class="border">{{ $tag->created_by }}</td>
                                <td class="border">
                                    <div class="flex items-center">
                                        <a class="flex items-center mr-3" href="{{ route('customers.tags.edit', $tag->id) }}">
                                            <i data-feather="check-square" class="w-4 h-4 mr-1"></i> {{ __('app.edit') }}
                                        </a>
                                        <a class="flex items-center text-theme-6" href="{{ route('customers.tags.delete', $tag->id) }}" data-toggle="modal" data-target="#delete-confirmation-modal">
                                            <i data-feather="trash-2" class="w-4 h-4 mr-1"></i> {{ __('app.delete') }}
                                        </a>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection