routes/admin.php
<?php
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin'], function () {
    Route::group(['namespace' => 'Auth', 'as' => 'auth.'], function () {
        Route::get('login', 'LoginController@showAdminLoginForm')->name('showLoginForm');
        Route::post('login', 'LoginController@adminLogin')->name('adminLogin');
        Route::post('logout', 'LoginController@adminLogout')->name('adminLogout');
    });


    Route::group(['middleware' => 'auth:admin'], function () {
        //
        Route::get('/', 'DashboardController@index')->name('home');
        Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
        Route::group(['prefix' => 'inventories', 'as' => 'inventories.'], function () {
            Route::get('/', 'InventoryController@dashboard')->name('dashboard');
            Route::group(['prefix' => 'valuation', 'as' => 'valuation.'], function () {
                Route::get('/', 'InventoryValuationController@index')->name('index');
                Route::get('/upload', 'InventoryValuationController@upload')->name('upload');
                Route::post('/upload', 'InventoryValuationController@uploadExcel')->name('upload_excel');
                Route::post('/start_import', 'InventoryValuationController@start_import')->name('start_import');
            });
        });
        Route::group(['prefix' => 'leads', 'as' => 'leads.'], function () {
            Route::get('/', 'LeadsController@dashboard')->name('dashboard');
            Route::get('/all', 'LeadsController@index')->name('index');
            Route::get('/create', 'LeadsController@create')->name('create');
            Route::get('/deleted', 'LeadsController@deleted')->name('deleted');
            Route::get('/import', 'LeadsController@import')->name('import');
            Route::get('/logs', 'LeadsController@logs')->name('logs');

            Route::get('/status', 'LeadsController@status')->name('status');
            Route::get('/status/create', 'LeadsController@statuscreate')->name('status.create');
            Route::post('/status/save', 'LeadsController@statussave')->name('status.save');
            Route::get('/status/edit/{id}', 'LeadsController@editstatus')->name('status.edit');
            Route::get('/status/delete/{id}', 'LeadsController@deletestatus')->name('status.delete');
            Route::get('/tags', 'LeadsController@tags')->name('tags');
            Route::get('/tags/create', 'LeadsController@createtags')->name('tags.create');
            Route::get('/tags/edit/{id}', 'LeadsController@edittags')->name('tags.edit');
            Route::get('/tags/delete/{id}', 'LeadsController@deletetags')->name('tags.delete');
            Route::post('/tags/save', 'LeadsController@savetags')->name('tags.save');
        });
        Route::group(['prefix' => 'customers', 'as' => 'customers.'], function () {
            Route::get('/', 'CustomersController@dashboard')->name('dashboard');
            Route::get('/all', 'CustomersController@index')->name('index');
            Route::get('/create', 'CustomersController@create')->name('create');
            Route::get('/deleted', 'CustomersController@deleted')->name('deleted');
            Route::get('/import', 'CustomersController@import')->name('import');
            Route::get('/logs', 'CustomersController@logs')->name('logs');

            Route::get('/status', 'CustomersController@status')->name('status');
            Route::get('/status/create', 'CustomersController@statuscreate')->name('status.create');
            Route::post('/status/save', 'CustomersController@statussave')->name('status.save');
            Route::get('/status/edit/{id}', 'CustomersController@editstatus')->name('status.edit');
            Route::get('/status/delete/{id}', 'CustomersController@deletestatus')->name('status.delete');
            Route::get('/tags', 'CustomersController@tags')->name('tags');
            Route::get('/tags/create', 'CustomersController@createtags')->name('tags.create');
            Route::get('/tags/edit/{id}', 'CustomersController@edittags')->name('tags.edit');
            Route::get('/tags/delete/{id}', 'CustomersController@deletetags')->name('tags.delete');
            Route::post('/tags/save', 'CustomersController@savetags')->name('tags.save');
        });
        Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
            Route::get('/', 'UsersController@dashboard')->name('dashboard');
            Route::get('/all', 'UsersController@index')->name('index');
            Route::get('/create', 'UsersController@create')->name('create');
            Route::get('/deleted', 'UsersController@deleted')->name('deleted');
            Route::get('/roles', 'UsersController@roles')->name('roles');
            Route::get('/logs', 'UsersController@logs')->name('logs');
        });
        Route::group(['prefix' => 'calendar', 'as' => 'calendar.'], function () {
            Route::get('/', 'CalendarController@dashboard')->name('dashboard');
            Route::get('/events', 'CalendarController@events')->name('events');
            Route::get('/types', 'CalendarController@types')->name('types');
            Route::get('/notifications', 'CalendarController@notifications')->name('notifications');
            Route::get('/logs', 'CalendarController@logs')->name('logs');
        });
        Route::group(['prefix' => 'locations', 'as' => 'locations.'], function () {
            Route::get('/', 'LocationController@index')->name('index');
            Route::get('/create', 'LocationController@create')->name('create');
            Route::get('/deleted', 'LocationController@deleted')->name('deleted');
            Route::get('/types', 'LocationController@types')->name('types');
            Route::get('/logs', 'LocationController@logs')->name('logs');
        });
        Route::group(['prefix' => 'reports', 'as' => 'reports.'], function () {
            Route::get('/logs', 'ReportController@logs')->name('logs');
        });
        Route::group(['prefix' => 'documents', 'as' => 'documents.'], function () {
            Route::get('/index', 'ReportController@index')->name('index');
            Route::get('/create', 'ReportController@create')->name('create');
            Route::get('/deleted', 'ReportController@deleted')->name('deleted');
            Route::get('/tags', 'ReportController@tags')->name('tags');
            Route::get('/logs', 'ReportController@logs')->name('logs');
        });
        Route::group(['prefix' => 'transactions', 'as' => 'transactions.'], function () {
            Route::get('/index', 'TransactionController@index')->name('index');
            Route::get('/create_invoice', 'TransactionController@create_invoice')->name('create_invoice');
            Route::get('/create_quote', 'TransactionController@create_quote')->name('create_quote');
            Route::get('/deleted', 'TransactionController@deleted')->name('deleted');
            Route::get('/tags', 'TransactionController@tags')->name('tags');
            Route::get('/logs', 'TransactionController@logs')->name('logs');
        });
        Route::group(['prefix' => 'settings', 'as' => 'settings.'], function () {
            Route::get('/profile', 'SettingsController@profile')->name('profile');
        });
    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Events\InventoryImportEvent;


Route::get('/inventory/share/{id}', 'OtherController@inventoryShare')->name('inventory.share');
Route::get('/thank_you', 'OtherController@thankyou')->name('thank_you');
Route::post('/inventory/leads/generate', 'OtherController@leadGenerate')->name('inventory.lead_generate');
Route::get('/facebook/webhooks/{category}', 'FacebookWebhookController@webhook');
Route::post('/facebook/webhooks/{category}', 'FacebookWebhookController@webhook');
Route::get('/remove_error_inventories', function () {
    foreach (App\Models\Inventory::all() as $inventory) {
        echo $inventory->price;
        echo '<br/>';
        if (!is_numeric($inventory->price)) {
            dd($inventory);
            $inventory->delete();
        }
    }
});
Route::get('/language/{lang}', function ($lang) {
    // return view('welcome');
    session(['my_locale' => $lang]);
    // dd(session('my_locale'));
    return redirect(route('home'));
})->name('language');
Route::get('/lang_currency', 'Controller@setLangCurrency')->name('lang_currency');


Route::group(['prefix' => 'valuation'], function () {
    Route::get('/search', 'ValuationController@search');
    Route::get('/makes', 'ValuationController@makes');
    Route::get('/filter_params', 'ValuationController@filter_params');
    Route::get('/{make}/models', 'ValuationController@models');
    Route::get('/{country}/cities', 'ValuationController@cities');
});
// makes

Route::group(['prefix' => 'car2db'], function () {
    //
    Route::get('/vehicle_types', 'Car2DBController@getVehicleTypes');
    Route::get('/transmissions', 'Car2DBController@transmissions');
    Route::get('/{type}/makes', 'Car2DBController@getMakes');
    Route::get('/{make}/models', 'Car2DBController@getModelsByMake');
    Route::get('/{type}/{make}/models', 'Car2DBController@getModels');
    Route::get('/{type}/{model}/generations', 'Car2DBController@getGenerations');
    Route::get('/{type}/{model}/{generation}/series', 'Car2DBController@getSeries');
    Route::get('/{type}/{model}/{serie}/trims', 'Car2DBController@getTrims');
    Route::get('/{type}/{trim}/equipments', 'Car2DBController@getEquipments');
    Route::get('/{type}/{trim}/specifications', 'Car2DBController@getSpecifications');
});

resources/views/layouts/common/admin/navbar.blade.php
<!-- Main navbar -->
	<div class="navbar navbar-expand-md navbar-light navbar-static">

		<!-- Header with logos -->
		<div class="navbar-header navbar-dark d-none d-md-flex align-items-md-center ">
			<div class="navbar-brand navbar-brand-md text-center">
				<a href="index.html" class="d-inline-block">
					<img src="{{ asset('global_assets/images/autobox365.png')}}" alt="">
				</a>
			</div>

			<div class="navbar-brand navbar-brand-xs">
				<a href="index.html" class="d-inline-block">
					<img src="{{ asset('global_assets/images/logo_icon_light.png')}}" alt="">
				</a>
			</div>
		</div>
		<!-- /header with logos -->


		<!-- Mobile controls -->
		<div class="d-flex flex-1 d-md-none">
			<div class="navbar-brand mr-auto">
				<a href="index.html" class="d-inline-block">
					<img src="{{ asset('global_assets/images/logo_dark.png')}}" alt="">
				</a>
			</div>

			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-mobile">
				<i class="icon-tree5"></i>
			</button>

			<button class="navbar-toggler sidebar-mobile-main-toggle" type="button">
				<i class="icon-paragraph-justify3"></i>
			</button>
		</div>
		<!-- /mobile controls -->


		<!-- Navbar content -->
		<div class="collapse navbar-collapse" id="navbar-mobile">
			<ul class="navbar-nav">
				<li class="nav-item">
					<a href="#" class="navbar-nav-link sidebar-control sidebar-main-toggle d-none d-md-block">
						<i class="icon-paragraph-justify3"></i>
					</a>
				</li>

				<li class="nav-item dropdown">
					<a href="#" class="navbar-nav-link dropdown-toggle caret-0" data-toggle="dropdown">
						<i class="icon-people"></i>
						<span class="d-md-none ml-2">Users</span>
						<span class="badge badge-mark border-pink-400 ml-auto ml-md-0"></span>
					</a>

					<div class="dropdown-menu dropdown-content wmin-md-300">
						<div class="dropdown-content-header">
							<span class="font-weight-semibold">Users online</span>
							<a href="#" class="text-default"><i class="icon-search4 font-size-base"></i></a>
						</div>

						<div class="dropdown-content-body dropdown-scrollable">
							<ul class="media-list">
								<li class="media">
									<div class="mr-3">
										<img src="{{ asset('global_assets/images/placeholders/placeholder.jpg')}}" width="36" height="36" class="rounded-circle" alt="">
									</div>
									<div class="media-body">
										<a href="#" class="media-title font-weight-semibold">Jordana Ansley</a>
										<span class="d-block text-muted font-size-sm">Lead web developer</span>
									</div>
									<div class="ml-3 align-self-center"><span class="badge badge-mark border-success"></span></div>
								</li>

								<li class="media">
									<div class="mr-3">
										<img src="{{ asset('global_assets/images/placeholders/placeholder.jpg')}}" width="36" height="36" class="rounded-circle" alt="">
									</div>
									<div class="media-body">
										<a href="#" class="media-title font-weight-semibold">Will Brason</a>
										<span class="d-block text-muted font-size-sm">Marketing manager</span>
									</div>
									<div class="ml-3 align-self-center"><span class="badge badge-mark border-danger"></span></div>
								</li>

								<li class="media">
									<div class="mr-3">
										<img src="{{ asset('global_assets/images/placeholders/placeholder.jpg')}}" width="36" height="36" class="rounded-circle" alt="">
									</div>
									<div class="media-body">
										<a href="#" class="media-title font-weight-semibold">Hanna Walden</a>
										<span class="d-block text-muted font-size-sm">Project manager</span>
									</div>
									<div class="ml-3 align-self-center"><span class="badge badge-mark border-success"></span></div>
								</li>

								<li class="media">
									<div class="mr-3">
										<img src="{{ asset('global_assets/images/placeholders/placeholder.jpg')}}" width="36" height="36" class="rounded-circle" alt="">
									</div>
									<div class="media-body">
										<a href="#" class="media-title font-weight-semibold">Dori Laperriere</a>
										<span class="d-block text-muted font-size-sm">Business developer</span>
									</div>
									<div class="ml-3 align-self-center"><span class="badge badge-mark border-warning-300"></span></div>
								</li>

								<li class="media">
									<div class="mr-3">
										<img src="{{ asset('global_assets/images/placeholders/placeholder.jpg')}}" width="36" height="36" class="rounded-circle" alt="">
									</div>
									<div class="media-body">
										<a href="#" class="media-title font-weight-semibold">Vanessa Aurelius</a>
										<span class="d-block text-muted font-size-sm">UX expert</span>
									</div>
									<div class="ml-3 align-self-center"><span class="badge badge-mark border-grey-400"></span></div>
								</li>
							</ul>
						</div>

						<div class="dropdown-content-footer bg-light">
							<a href="#" class="text-grey mr-auto">All users</a>
							<a href="#" class="text-grey"><i class="icon-gear"></i></a>
						</div>
					</div>
				</li>
			</ul>

			<span class="badge bg-pink-400 badge-pill ml-md-3 mr-md-auto">16 orders</span>

			<ul class="navbar-nav">
				<li class="nav-item dropdown">
					<a href="#" class="navbar-nav-link dropdown-toggle" data-toggle="dropdown">
						<img src="{{ asset('global_assets/images/lang/gb.png')}}" class="img-flag mr-2" alt="">
						English
					</a>

					<div class="dropdown-menu dropdown-menu-right">
						<a href="#" class="dropdown-item english active"><img src="{{ asset('global_assets/images/lang/gb.png')}}" class="img-flag" alt=""> English</a>
						<a href="#" class="dropdown-item ukrainian"><img src="{{ asset('global_assets/images/lang/ua.png')}}" class="img-flag" alt=""> Українська</a>
						<a href="#" class="dropdown-item deutsch"><img src="{{ asset('global_assets/images/lang/de.png')}}" class="img-flag" alt=""> Deutsch</a>
						<a href="#" class="dropdown-item espana"><img src="{{ asset('global_assets/images/lang/es.png')}}" class="img-flag" alt=""> España</a>
						<a href="#" class="dropdown-item russian"><img src="{{ asset('global_assets/images/lang/ru.png')}}" class="img-flag" alt=""> Русский</a>
					</div>
				</li>

				<li class="nav-item dropdown">
					<a href="#" class="navbar-nav-link dropdown-toggle caret-0" data-toggle="dropdown">
						<i class="icon-bubbles4"></i>
						<span class="d-md-none ml-2">Messages</span>
						<span class="badge badge-mark border-pink-400 ml-auto ml-md-0"></span>
					</a>

					<div class="dropdown-menu dropdown-menu-right dropdown-content wmin-md-350">
						<div class="dropdown-content-header">
							<span class="font-weight-semibold">Messages</span>
							<a href="#" class="text-default"><i class="icon-compose"></i></a>
						</div>

						<div class="dropdown-content-body dropdown-scrollable">
							<ul class="media-list">
								<li class="media">
									<div class="mr-3 position-relative">
										<img src="{{ asset('global_assets/images/placeholders/placeholder.jpg')}}" width="36" height="36" class="rounded-circle" alt="">
									</div>

									<div class="media-body">
										<div class="media-title">
											<a href="#">
												<span class="font-weight-semibold">James Alexander</span>
												<span class="text-muted float-right font-size-sm">04:58</span>
											</a>
										</div>

										<span class="text-muted">who knows, maybe that would be the best thing for me...</span>
									</div>
								</li>

								<li class="media">
									<div class="mr-3 position-relative">
										<img src="{{ asset('global_assets/images/placeholders/placeholder.jpg')}}" width="36" height="36" class="rounded-circle" alt="">
									</div>

									<div class="media-body">
										<div class="media-title">
											<a href="#">
												<span class="font-weight-semibold">Margo Baker</span>
												<span class="text-muted float-right font-size-sm">12:16</span>
											</a>
										</div>

										<span class="text-muted">That was something he was unable to do because...</span>
									</div>
								</li>

								<li class="media">
									<div class="mr-3">
										<img src="{{ asset('global_assets/images/placeholders/placeholder.jpg')}}" width="36" height="36" class="rounded-circle" alt="">
									</div>
									<div class="media-body">
										<div class="media-title">
											<a href="#">
												<span class="font-weight-semibold">Jeremy Victorino</span>
												<span class="text-muted float-right font-size-sm">22:48</span>
											</a>
										</div>

										<span class="text-muted">But that would be extremely strained and suspicious...</span>
									</div>
								</li>

								<li class="media">
									<div class="mr-3">
										<img src="{{ asset('global_assets/images/placeholders/placeholder.jpg')}}" width="36" height="36" class="rounded-circle" alt="">
									</div>
									<div class="media-body">
										<div class="media-title">
											<a href="#">
												<span class="font-weight-semibold">Beatrix Diaz</span>
												<span class="text-muted float-right font-size-sm">Tue</span>
											</a>
										</div>

										<span class="text-muted">What a strenuous career it is that I've chosen...</span>
									</div>
								</li>

								<li class="media">
									<div class="mr-3">
										<img src="{{ asset('global_assets/images/placeholders/placeholder.jpg')}}" width="36" height="36" class="rounded-circle" alt="">
									</div>
									<div class="media-body">
										<div class="media-title">
											<a href="#">
												<span class="font-weight-semibold">Richard Vango</span>
												<span class="text-muted float-right font-size-sm">Mon</span>
											</a>
										</div>

										<span class="text-muted">Other travelling salesmen live a life of luxury...</span>
									</div>
								</li>
							</ul>
						</div>

						<div class="dropdown-content-footer bg-light">
							<a href="#" class="text-grey mr-auto">All messages</a>
							<div>
								<a href="#" class="text-grey" data-popup="tooltip" title="Mark all as read"><i class="icon-radio-unchecked"></i></a>
								<a href="#" class="text-grey ml-2" data-popup="tooltip" title="Settings"><i class="icon-cog3"></i></a>
							</div>
						</div>
					</div>
				</li>

				<li class="nav-item dropdown dropdown-user">
					<a href="#" class="navbar-nav-link d-flex align-items-center dropdown-toggle" data-toggle="dropdown">
						<img src="{{ asset('global_assets/images/placeholders/placeholder.jpg')}}" class="rounded-circle mr-2" height="34" alt="">
						<span>{{ Auth::user()->name }}</span>
					</a>

					<div class="dropdown-menu dropdown-menu-right">
						<a href="#" class="dropdown-item"><i class="icon-user-plus"></i> My profile</a>
						<a href="#" class="dropdown-item"><i class="icon-coins"></i> My balance</a>
						<a href="#" class="dropdown-item"><i class="icon-comment-discussion"></i> Messages <span class="badge badge-pill bg-indigo-400 ml-auto">58</span></a>
						<div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item"><i class="icon-cog5"></i> Account settings</a>
                        <form id="logout-form" action="{{ route('admin.auth.adminLogout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        <a  href="{{ route('admin.auth.adminLogout') }}"
                            onclick="event.preventDefault();
                                        document.getElementById('logout-form').submit();" class="dropdown-item">
                            <i class="icon-switch2"></i>
                            <span>{{ __('Logout') }}</span>
                        </a>
					</div>
				</li>
			</ul>
		</div>
		<!-- /navbar content -->

	</div>
	<!-- /main navbar -->

resources/views/layouts/common/admin/sidebar.blade.php
<!-- Main sidebar -->
<div class="sidebar sidebar-dark sidebar-main sidebar-expand-md">

    <!-- Sidebar mobile toggler -->
    <div class="sidebar-mobile-toggler text-center">
        <a href="#" class="sidebar-mobile-main-toggle">
            <i class="icon-arrow-left8"></i>
        </a>
        Navigation
        <a href="#" class="sidebar-mobile-expand">
            <i class="icon-screen-full"></i>
            <i class="icon-screen-normal"></i>
        </a>
    </div>
    <!-- /sidebar mobile toggler -->
    <!-- Sidebar content -->
    <div class="sidebar-content">

        <!-- User menu -->
        <div class="sidebar-user-material">
            <div class="sidebar-user-material-body">
                <div class="card-body text-center">
                    <a href="#">
                        <img src="{{ asset('global_assets/images/placeholders/placeholder.jpg') }}"
                            class="img-fluid rounded-circle shadow-1 mb-3" width="80" height="80" alt="">
                    </a>
                    <h6 class="mb-0 text-white text-shadow-dark">{{ Auth::user()->first_name }}
                        {{ Auth::user()->last_name }}</h6>
                    <span class="font-size-sm text-white text-shadow-dark">Santa Ana, CA</span>
                </div>


            </div>


        </div>
        <!-- /user menu -->


        <!-- Main navigation -->
        <div class="card card-sidebar-mobile">
            <ul class="nav nav-sidebar" data-nav-type="accordion">
                <li class="nav-item">
                    <a href="{{ route('admin.home') }}" class="nav-link active">
                        <i class="fas fa-tachometer-alt"></i>
                        <span>
                            {{ __('menu.dashboard') }}
                        </span>
                    </a>
                </li>
                <li
                    class="nav-item nav-item-submenu {{ Route::is('admin.inventories.*') ? 'open nav-item-open' : '' }}">
                    <a href="#" class="nav-link"><i class="fas fa-car"></i>
                        <span>{{ __('menu.inventories.inventory') }}</span><span
                            class="badge badge-pill bg-blue-400 align-self-center ml-auto">2.2</span></a>
                    <ul class="nav nav-group-sub" data-submenu-title="Layouts"
                        style="display: {{ Route::is('admin.inventories.*') ? 'block' : 'none' }};">
                        <li class="nav-item"><a href="{{ route('admin.inventories.valuation.index') }}"
                                class="nav-link {{ Route::is('admin.inventories.valuation.index') ? 'active' : '' }}">{{ __('app.valuation') }}</a>
                        </li>

                    </ul>
                </li>



                <!-- /main -->


            </ul>
        </div>
        <!-- /main navigation -->

    </div>
    <!-- /sidebar content -->

</div>
<!-- /main sidebar -->